"use client"; // Uncomment this if using Next.js 13 App Router with client components
import { Box, Typography, Avatar, Stack, Tooltip } from "@mui/material";
import { motion, useInView } from "framer-motion";
import { useRef } from "react";

export default function ProcessSuspender() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-100px" });

  return (
    <motion.div ref={ref}>
      <Stack
        spacing={{ xs: 4, sm: 10 }}
        direction={{ xs: "column", sm: "row" }}
        alignItems="center"
      >
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.8, ease: "easeOut" }}
        >
          <Tooltip title="Cybercafe picture generated by AI.">
            <Avatar
              src="/about-me/cyber-cafe.png"
              sx={{
                width: { xs: 180, sm: 200, md: 250 },
                height: { xs: 180, sm: 200, md: 250 },
                borderRadius: 3,
                mx: "auto",
              }}
            />
          </Tooltip>
        </motion.div>

        <Box
          sx={{
            px: { xs: 2, sm: 4 },
            py: 2,
            justifyContent: "center",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={isInView ? { opacity: 1, y: 0 } : {}}
            transition={{ duration: 0.8, ease: "easeOut", type: "spring", stiffness: 120 }}
          >
            <Typography
              variant="h6"
              fontWeight="bold"
              gutterBottom
              sx={{
                fontSize: { xs: "1.25rem", sm: "1.5rem", md: "2rem" },
                textShadow: "2px 2px 4px rgba(0,0,0,0.3)",
                letterSpacing: "2px",
                ml: 4,
              }}
            >
              Process Suspender
            </Typography>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 1, ease: "easeOut" }}
          >
            <Typography
              variant="body1"
              paragraph
              sx={{ fontSize: { xs: "0.875rem", sm: "1rem", md: "1.125rem" } }}
            >
              After that, I transitioned to living among civilians and experienced life as any typical child. It was during this time that I began to skip school and spend countless hours at cyber cafés, which were booming businesses at the time.
            </Typography>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={isInView ? { opacity: 1, x: 0 } : {}}
            transition={{ duration: 1, ease: "easeOut", delay: 0.3 }}
          >
            <Typography
              variant="body1"
              paragraph
              sx={{ fontSize: { xs: "0.875rem", sm: "1rem", md: "1.125rem" } }}
            >
              However, the issue was that I needed money to keep returning to the cyber café. This led me to discover a tool called <strong>Process Suspender</strong>, which allowed me to stop selected background processes. In my case, I used it for hacking purposes.
            </Typography>
          </motion.div>
        </Box>
      </Stack>
    </motion.div>
  );
}
